title: Lam Cheok Weng's Homepage
page-top-title: Lam Cheok Weng
top-section-bg-text: Computer Science
home-subtitle: Lam Cheok Weng &ensp;|&ensp;林卓穎
copyright-text: '&copy; Lam Cheok Weng 2025-2025. All Rights Reserved.'
